CREATE DATABASE student;
USE student;

CREATE TABLE persons (
    PersonID INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(100) NOT NULL,
    Surname VARCHAR(100) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    City VARCHAR(100) NOT NULL,
    BirthDate DATE NOT NULL,
    PRIMARY KEY (PersonID)
);
